package sage.springcoder.jamhuborderservice.domain;

public enum JamOrderEventEnum {

    VALIDATE_ORDER, CANCEL_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    JAMORDER_PICKED_UP
}
